travis:
  secure:
    BINSTAR_TOKEN: eUf+pV7uFNn8bu9PXgb6PBUBbs8znf4BKcDO7P8OGChgT55cNbPuDKKVr/f9DE/eu40KMtxvnGpLgrdfgV/6QTFo1mb3HbJYe3Uu2KPKn6CcHr6ccapu8cQMW3eK5+FoNXfN7mHDySbR6594oQNk/e0KWedYqI4ydGMmdV3WNL7OUfmmiKWYJO1G8vSk1wtvxDdx4+2vU+Vd89HSXs3TmGI1R2PqBwDrX7UOkRZ0QIHu0uQekhmgsTRajaOapblWMNOx6USc58RUwsjgs/H4N/l7nZewgr3yeuC3vobhgx7ntq5scwLxKP7mYxm1b782B1Ppea/HhBaS3bkqmab3/ZWaVTejcs8qBRkZXgv20RMDW8E5TXGZmtIv4z/LhLf4KEbdOECLHP5HGPKufSddiOqfJnrEudks9xZppOsAGvjHMz/yt6jbOZPwsZ2c+CamUo3BsWJyP/TdmX/QmiezT8BUS/R6XLiP6SVpKg1OWK56K3X+hJbvZ4tNrG3ttRBY7uhj8WQMVAJQBhE0QGCSRAIy2FDQEB+eeggeSslaBsuPqsqi6i3QpXglqGHF1I6X3JAFhykgr2rChwTVHgG2w9IEP8W3sWTLq15oBuIsU4gT4aFBH5Ic33xtye8Jjjo262UV5wIRTnxoUjP3BuSAac+QNTinhcuARRz5Mpc6QaY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
