appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Qm0Mq1v2l2YJAQC4L94QnVjIpOcrqz2fdbpxNJqsbk3sJkHYWGZRDjPu1vqfxtA/iO2uh68DLZY4voxZ9hZoE3Rs8LB3EdVMeyVyYQCt7NsZJzphnJYrOd7RYCApIS21uMn0U+33pQr4q+MpHD2vWSTq0C2tpWGI6tH6J2uMUIiR0XSO1ECNsTT95xNyft2rGKNjoBivDxDGg2hL4G4iChFwPzFrHkSNicGrx8W5WhKKQf26nl/w6N/iLWFxnPd7yKOoPe6VtRy0RLghqkMWBBAE6zxznZ5fCUGBoJ/U+yjmj7mwKGLVKO4JB/CtB1srpg8agQqEbfKpynmTHOSxnR6zfIllKZKwpg04fKkicPPOosKQpy5xV4Pjhj5BFsizQFIaKtFYMKnrunCcyVR04thoF3lBIJQ16BgF5TKr5FszRIru4cGqx0CoqCKRYaAiH4pXn1Y1L3Lo2pE6iiBPJKRANuUsQi+6DNLRtIexw/S4euSBR2ypaFOZ9O5CnqdjpFYIAymYnE6PAo2Uh8Be9mv8b/nukx/eyakSrGsF2X07gAhenK2FWLgOqKC3+sr4xhzQ0GCX+SthbQhU0z1oE5d+861Mmke4A0YNe7XmItgyK8SaSawNwrKcS8g/R38S3+nDtRXceLlGgpfeRNb4EMdCE5Rf9iI2gdfTWBkKyNM=}
conda_forge_output_validation: true
